displayName=Boss HP Bar Adjustments
author=Cleg Drop
support=https://github.com/ClegDrop/Boss-Bar-Offset
description=Adjust the boss HP bar vertical position at top-middle.
tags=boss,raid,health,pvm,cox,tob,toa
version=1.1
plugins=clegdrop.bossbaroffset.BossBarOffsetPlugin
build=standard